/**
 * Enhancement Suggestions Task
 * Task instructions for providing enhancement suggestions for prompts
 *
 * Version: 1
 * Last updated: 2026-01-24T21:47:18.068Z
 *
 * @generated by ForPrompt CLI - Do not edit manually
 */

export const task_enhancement_suggestions = "<task>\nProvide 3-5 specific, actionable enhancement suggestions for the system prompt.\n</task>\n\n<suggestion_framework>\nFor each suggestion, you must:\n1. **Identify**: Pinpoint a specific weakness, gap, or missed opportunity\n2. **Explain**: Why this matters for prompt effectiveness\n3. **Provide**: The exact replacement or additional text to use\n</suggestion_framework>\n\n<focus_areas>\nPrioritize improvements in these areas:\n- **Clarity**: Ambiguous instructions that could be misinterpreted\n- **Edge Cases**: Missing error handling or unusual scenario coverage\n- **Tool Usage**: Incomplete or unclear tool instructions (if applicable)\n- **Output Format**: Vague or missing format specifications\n- **Real-World Gaps**: Scenarios the prompt doesn't handle well\n- **Structure**: Poor organization or missing sections\n</focus_areas>\n\n<priority_levels>\n- `high`: Critical issues that significantly impact prompt effectiveness\n- `medium`: Important improvements that would enhance quality\n- `low`: Nice-to-have refinements for polish\n</priority_levels>\n\n<output_format>\nCRITICAL: Respond with ONLY valid JSON. No markdown, no explanation.\n\n{\n  \"suggestions\": [\n    {\n      \"id\": \"unique-id-1\",\n      \"issue\": \"Brief, specific issue description\",\n      \"suggestion\": \"Why this matters and what to do about it\",\n      \"enhancedText\": \"Exact text to add or replace\",\n      \"priority\": \"high\"\n    }\n  ]\n}\n</output_format>";

export const task_enhancement_suggestionsInfo = {
  key: "task_enhancement_suggestions",
  name: "Enhancement Suggestions Task",
  version: 1,
  updatedAt: 1769291238068,
} as const;

export default task_enhancement_suggestions;
