/**
 * Field: Tools Notes
 * Enhancement prompt for the toolsNotes field
 *
 * Version: 1
 * Last updated: 2026-01-24T21:48:21.321Z
 *
 * @generated by ForPrompt CLI - Do not edit manually
 */

export const field_tools_notes = "Clarify this tool usage strategy.\n\nRules:\n- Specify when to use each tool\n- Note the order of operations if relevant\n- Include fallback behavior\n- Mention any tool limitations\n- Keep it practical for the AI to follow\n\nTEXT TO IMPROVE:\n{{fieldValue}}\n\nReturn ONLY the improved text.";

export const field_tools_notesInfo = {
  key: "field_tools_notes",
  name: "Field: Tools Notes",
  version: 1,
  updatedAt: 1769291301321,
} as const;

export default field_tools_notes;
