/**
 * Field: Input Format
 * Enhancement prompt for the inputFormat field
 *
 * Version: 1
 * Last updated: 2026-01-24T21:47:57.513Z
 *
 * @generated by ForPrompt CLI - Do not edit manually
 */

export const field_input_format = "Clarify this input format specification.\n\nRules:\n- Describe the expected input structure\n- Include examples of valid inputs if helpful\n- Mention any required fields or formats\n- Note edge cases to handle\n- Keep it practical\n\nTEXT TO IMPROVE:\n{{fieldValue}}\n\nReturn ONLY the improved text.";

export const field_input_formatInfo = {
  key: "field_input_format",
  name: "Field: Input Format",
  version: 1,
  updatedAt: 1769291277513,
} as const;

export default field_input_format;
