/**
 * ForPrompt - Auto-generated prompt exports
 *
 * @generated by ForPrompt CLI - Do not edit manually
 * Generated at: 2026-01-24T22:34:08.777Z
 */

export { base_prompt_engineer, base_prompt_engineerInfo } from "./base_prompt_engineer/prompt";
export { task_generation, task_generationInfo } from "./task_generation/prompt";
export { task_analysis, task_analysisInfo } from "./task_analysis/prompt";
export { task_enhancement, task_enhancementInfo } from "./task_enhancement/prompt";
export { task_enhancement_suggestions, task_enhancement_suggestionsInfo } from "./task_enhancement_suggestions/prompt";
export { task_extraction, task_extractionInfo } from "./task_extraction/prompt";
export { task_edit, task_editInfo } from "./task_edit/prompt";
export { field_purpose, field_purposeInfo } from "./field_purpose/prompt";
export { field_expected_behavior, field_expected_behaviorInfo } from "./field_expected_behavior/prompt";
export { field_input_format, field_input_formatInfo } from "./field_input_format/prompt";
export { field_output_format, field_output_formatInfo } from "./field_output_format/prompt";
export { field_constraints, field_constraintsInfo } from "./field_constraints/prompt";
export { field_use_cases, field_use_casesInfo } from "./field_use_cases/prompt";
export { field_additional_notes, field_additional_notesInfo } from "./field_additional_notes/prompt";
export { field_tools_notes, field_tools_notesInfo } from "./field_tools_notes/prompt";
export { report_conversation_analysis, report_conversation_analysisInfo } from "./report_conversation_analysis/prompt";
export { report_batch, report_batchInfo } from "./report_batch/prompt";
export { report_version, report_versionInfo } from "./report_version/prompt";

import { base_prompt_engineer, task_generation, task_analysis, task_enhancement, task_enhancement_suggestions, task_extraction, task_edit, field_purpose, field_expected_behavior, field_input_format, field_output_format, field_constraints, field_use_cases, field_additional_notes, field_tools_notes, report_conversation_analysis, report_batch, report_version } from "./";

/**
 * All prompts as a map for dynamic access
 */
export const prompts = {
  "base_prompt_engineer": base_prompt_engineer,
  "task_generation": task_generation,
  "task_analysis": task_analysis,
  "task_enhancement": task_enhancement,
  "task_enhancement_suggestions": task_enhancement_suggestions,
  "task_extraction": task_extraction,
  "task_edit": task_edit,
  "field_purpose": field_purpose,
  "field_expected_behavior": field_expected_behavior,
  "field_input_format": field_input_format,
  "field_output_format": field_output_format,
  "field_constraints": field_constraints,
  "field_use_cases": field_use_cases,
  "field_additional_notes": field_additional_notes,
  "field_tools_notes": field_tools_notes,
  "report_conversation_analysis": report_conversation_analysis,
  "report_batch": report_batch,
  "report_version": report_version,
} as const;

/**
 * Get a prompt by key
 */
export function getPrompt(key: keyof typeof prompts): string {
  return prompts[key];
}

export type PromptKey = keyof typeof prompts;
