packages:
  - apps/*
  - packages/*
  - '!packages/sdk-python'
  - tooling/*

catalog:
  '@eslint/js': ^10.0.1
  '@tailwindcss/postcss': ^4.2.1
  '@tailwindcss/vite': ^4.1.16
  '@tanstack/react-form': ^1.28.3
  '@types/node': 25.3.2
  '@vitejs/plugin-react': 5.1.4
  eslint: ^10.0.2
  prettier: ^3.6.2
  tailwindcss: 4.2.1
  typescript: ^5.9.3
  vite: 7.3.1
  zod: ^4.1.12

catalogs:
  react19:
    '@types/react': ~19.2.14
    '@types/react-dom': ~19.2.3
    react: 19.2.4
    react-dom: 19.2.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  '@types/minimatch': 5.1.2
  lightningcss: 1.30.1
  vite: 7.3.1

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
