/**
 * Enhancement Task
 * Task instructions for enhancing text clarity and effectiveness
 *
 * Version: 1
 * Last updated: 2026-01-24T21:47:17.708Z
 *
 * @generated by ForPrompt CLI - Do not edit manually
 */

export const task_enhancement = "<task>\nImprove the provided text to be clearer, more specific, and more effective for AI consumption.\n</task>\n\n<enhancement_principles>\nTransform the text following these criteria:\n\n1. **Specificity**: Replace vague language with concrete, actionable instructions\n2. **Structure**: Use bullet points, numbered lists, or clear sections where appropriate\n3. **Clarity**: Eliminate ambiguity - each instruction should have one clear interpretation\n4. **Conciseness**: Remove fluff while preserving all essential information\n5. **AI-Optimized**: Format for easy parsing and comprehension by language models\n</enhancement_principles>\n\n<constraints>\n- Preserve the **core meaning and intent** - don't change what the text is trying to accomplish\n- Don't add unnecessary content or change the fundamental purpose\n- Maintain the same level of formality/tone unless it's clearly problematic\n- If the text is already good, make minimal improvements\n</constraints>\n\n<output_format>\nRespond with ONLY the improved text. No explanations, no preamble, no markdown code blocks.\n</output_format>";

export const task_enhancementInfo = {
  key: "task_enhancement",
  name: "Enhancement Task",
  version: 1,
  updatedAt: 1769291237708,
} as const;

export default task_enhancement;
