/**
 * Field: Expected Behavior
 * Enhancement prompt for the expectedBehavior field
 *
 * Version: 1
 * Last updated: 2026-01-24T21:47:57.148Z
 *
 * @generated by ForPrompt CLI - Do not edit manually
 */

export const field_expected_behavior = "Improve this behavior description to be clear and implementable.\n\nRules:\n- Use concrete behavioral guidelines\n- Specify tone (formal, casual, friendly, professional)\n- Include what NOT to do if relevant\n- Use short bullet points if multiple behaviors\n- Avoid vague terms like \"be helpful\" or \"be nice\"\n\nEXAMPLE:\nBefore: \"Be helpful and professional\"\nAfter: \"- Respond in a friendly, professional tone\\n- Ask clarifying questions before making assumptions\\n- Acknowledge user frustration without being defensive\\n- Never promise specific timelines without verification\"\n\nTEXT TO IMPROVE:\n{{fieldValue}}\n\nReturn ONLY the improved text.";

export const field_expected_behaviorInfo = {
  key: "field_expected_behavior",
  name: "Field: Expected Behavior",
  version: 1,
  updatedAt: 1769291277148,
} as const;

export default field_expected_behavior;
