/**
 * Field: Use Cases
 * Enhancement prompt for the useCases field
 *
 * Version: 1
 * Last updated: 2026-01-24T21:48:20.606Z
 *
 * @generated by ForPrompt CLI - Do not edit manually
 */

export const field_use_cases = "Transform these use cases into concrete scenarios.\n\nRules:\n- Write as brief scenario descriptions\n- Include the user's goal in each\n- Make them diverse (cover different situations)\n- Keep each to 1 line\n- 3-5 scenarios is ideal\n\nEXAMPLE:\nBefore: \"Help with orders and returns\"\nAfter: \"- Customer wants to track a delayed shipment\\n- User needs to return a damaged item\\n- Customer asks about product compatibility\\n- User wants to modify an order before shipping\"\n\nTEXT TO IMPROVE:\n{{fieldValue}}\n\nReturn ONLY the improved text.";

export const field_use_casesInfo = {
  key: "field_use_cases",
  name: "Field: Use Cases",
  version: 1,
  updatedAt: 1769291300606,
} as const;

export default field_use_cases;
