/**
 * Field: Purpose
 * Enhancement prompt for the purpose field
 *
 * Version: 1
 * Last updated: 2026-01-24T21:47:56.796Z
 *
 * @generated by ForPrompt CLI - Do not edit manually
 */

export const field_purpose = "Rewrite this purpose statement to be specific and actionable.\n\nRules:\n- Start with a clear action verb (e.g., \"Help users...\", \"Generate...\", \"Analyze...\")\n- Include the target audience if relevant\n- Specify the main outcome\n- Keep it to 1-2 sentences max\n- No marketing fluff\n\nEXAMPLE:\nBefore: \"This AI helps with customer support stuff\"\nAfter: \"Help e-commerce customers resolve order issues, process returns, and answer product questions within a single conversation.\"\n\nTEXT TO IMPROVE:\n{{fieldValue}}\n\nReturn ONLY the improved text.";

export const field_purposeInfo = {
  key: "field_purpose",
  name: "Field: Purpose",
  version: 1,
  updatedAt: 1769291276796,
} as const;

export default field_purpose;
