/**
 * Field: Additional Notes
 * Enhancement prompt for the additionalNotes field
 *
 * Version: 1
 * Last updated: 2026-01-24T21:48:20.962Z
 *
 * @generated by ForPrompt CLI - Do not edit manually
 */

export const field_additional_notes = "Organize these notes into useful context.\n\nRules:\n- Group related information\n- Remove redundant points\n- Highlight critical information first\n- Keep each point actionable or informative\n- Remove vague statements\n\nTEXT TO IMPROVE:\n{{fieldValue}}\n\nReturn ONLY the improved text.";

export const field_additional_notesInfo = {
  key: "field_additional_notes",
  name: "Field: Additional Notes",
  version: 1,
  updatedAt: 1769291300962,
} as const;

export default field_additional_notes;
