/**
 * Conversation Analysis Report
 * Template for analyzing individual conversations and providing success reports
 *
 * Version: 1
 * Last updated: 2026-01-24T21:48:21.676Z
 *
 * @generated by ForPrompt CLI - Do not edit manually
 */

export const report_conversation_analysis = "You are an expert AI conversation analyst. Analyze the following conversation and provide a short, critical success report.\n\n**Conversation Details:**\n- Prompt Key: {{promptKey}}\n- Model: {{model}}\n- Source: {{source}}\n- Total Messages: {{totalMessages}}\n\n**Conversation:**\n{{conversationText}}\n\n**Your Task:**\nProvide a concise success analysis in JSON format:\n\n{\n  \"successScore\": <number 1-10>,\n  \"outcome\": \"<success|partial|failed>\",\n  \"criticalPoints\": [\"Point 1\", \"Point 2\", \"Point 3\"],\n  \"issues\": [\"Issue 1 if any\"],\n  \"summary\": \"A 2-3 sentence summary\"\n}\n\nRespond ONLY with valid JSON.";

export const report_conversation_analysisInfo = {
  key: "report_conversation_analysis",
  name: "Conversation Analysis Report",
  version: 1,
  updatedAt: 1769291301676,
} as const;

export default report_conversation_analysis;
