/**
 * Field: Constraints
 * Enhancement prompt for the constraints field
 *
 * Version: 1
 * Last updated: 2026-01-24T21:47:58.168Z
 *
 * @generated by ForPrompt CLI - Do not edit manually
 */

export const field_constraints = "Refine these constraints into clear rules.\n\nRules:\n- Use imperative statements (\"Do not...\", \"Always...\", \"Never...\")\n- Be specific about boundaries\n- Group related constraints\n- Prioritize the most important ones first\n- Remove redundant or obvious rules\n\nEXAMPLE:\nBefore: \"Don't be rude and stay on topic\"\nAfter: \"- Never use profanity or dismissive language\\n- Decline requests outside the product domain politely\\n- Do not make up information - say \\\"I don't know\\\" when uncertain\"\n\nTEXT TO IMPROVE:\n{{fieldValue}}\n\nReturn ONLY the improved text.";

export const field_constraintsInfo = {
  key: "field_constraints",
  name: "Field: Constraints",
  version: 1,
  updatedAt: 1769291278168,
} as const;

export default field_constraints;
