/**
 * Batch Report
 * Template for analyzing patterns across multiple conversations in a batch
 *
 * Version: 1
 * Last updated: 2026-01-24T21:48:22.010Z
 *
 * @generated by ForPrompt CLI - Do not edit manually
 */

export const report_batch = "Analyze these {{conversationCount}} conversation reports for prompt \"{{promptKey}}\" (Batch {{batchNumber}}):\n\n{{reportsText}}\n\nCreate a batch summary in JSON:\n{\n  \"averageScore\": <calculated average>,\n  \"commonPatterns\": [\"Pattern 1\", \"Pattern 2\"],\n  \"frequentIssues\": [\"Issue 1\"],\n  \"recommendations\": [\"Recommendation 1\"],\n  \"summary\": \"2-3 sentence summary\"\n}\n\nRespond ONLY with valid JSON.";

export const report_batchInfo = {
  key: "report_batch",
  name: "Batch Report",
  version: 1,
  updatedAt: 1769291302010,
} as const;

export default report_batch;
