/**
 * Field: Output Format
 * Enhancement prompt for the outputFormat field
 *
 * Version: 1
 * Last updated: 2026-01-24T21:47:57.843Z
 *
 * @generated by ForPrompt CLI - Do not edit manually
 */

export const field_output_format = "Improve this output format specification.\n\nRules:\n- Be explicit about structure (JSON, markdown, plain text)\n- Include field names if structured output\n- Specify any required sections\n- Note maximum lengths if relevant\n- Give a mini-example if complex\n\nTEXT TO IMPROVE:\n{{fieldValue}}\n\nReturn ONLY the improved text.";

export const field_output_formatInfo = {
  key: "field_output_format",
  name: "Field: Output Format",
  version: 1,
  updatedAt: 1769291277843,
} as const;

export default field_output_format;
