/**
 * Version Report
 * Template for creating overall success reports across all batches
 *
 * Version: 1
 * Last updated: 2026-01-24T21:48:22.350Z
 *
 * @generated by ForPrompt CLI - Do not edit manually
 */

export const report_version = "Create an overall success report for prompt \"{{promptKey}}\" v{{versionNumber}}.\n\nTotal: {{totalConversations}} conversations across {{batchCount}} batches.\n\n{{batchesText}}\n\nJSON format:\n{\n  \"overallSuccessRate\": <percentage 0-100>,\n  \"averageScore\": <average>,\n  \"keyInsights\": [\"Insight 1\", \"Insight 2\"],\n  \"improvementSuggestions\": [\"Suggestion 1\"],\n  \"strengthsIdentified\": [\"Strength 1\"],\n  \"weaknessesIdentified\": [\"Weakness 1\"],\n  \"summary\": \"3-4 sentence comprehensive summary\"\n}\n\nRespond ONLY with valid JSON.";

export const report_versionInfo = {
  key: "report_version",
  name: "Version Report",
  version: 1,
  updatedAt: 1769291302350,
} as const;

export default report_version;
