/**
 * TypeScript format generator
 */

import type { Prompt } from "../types";

/**
 * Generate TypeScript file content from prompts
 */
export function generateTypeScript(prompts: Prompt[], syncedAt: number): string {
  const timestamp = new Date(syncedAt).toISOString();

  // Generate the prompts object
  const promptsObj = prompts.map((prompt) => {
    const systemPrompt = prompt.systemPrompt
      .replace(/\\/g, "\\\\")
      .replace(/`/g, "\\`")
      .replace(/\$/g, "\\$");

    return `  ${JSON.stringify(prompt.key)}: {
    key: ${JSON.stringify(prompt.key)},
    name: ${JSON.stringify(prompt.name)},
    ${prompt.description ? `description: ${JSON.stringify(prompt.description)},` : ""}
    versionNumber: ${prompt.versionNumber},
    systemPrompt: \`${systemPrompt}\`,
    updatedAt: ${prompt.updatedAt},
    ${prompt.purpose ? `purpose: ${JSON.stringify(prompt.purpose)},` : ""}
    ${prompt.expectedBehavior ? `expectedBehavior: ${JSON.stringify(prompt.expectedBehavior)},` : ""}
    ${prompt.inputFormat ? `inputFormat: ${JSON.stringify(prompt.inputFormat)},` : ""}
    ${prompt.outputFormat ? `outputFormat: ${JSON.stringify(prompt.outputFormat)},` : ""}
    ${prompt.constraints ? `constraints: ${JSON.stringify(prompt.constraints)},` : ""}
    ${prompt.useCases ? `useCases: ${JSON.stringify(prompt.useCases)},` : ""}
    ${prompt.additionalNotes ? `additionalNotes: ${JSON.stringify(prompt.additionalNotes)},` : ""}
    ${prompt.toolsNotes ? `toolsNotes: ${JSON.stringify(prompt.toolsNotes)},` : ""}
  }`;
  }).join(",\n");

  return `// Auto-generated by ForPrompt SDK - DO NOT EDIT
// Last synced: ${timestamp}

export const prompts = {
${promptsObj}
} as const;

export type PromptKey = keyof typeof prompts;

/**
 * Get a prompt by its key
 */
export function getPrompt(key: PromptKey) {
  return prompts[key];
}

/**
 * Get all prompt keys
 */
export function getPromptKeys(): PromptKey[] {
  return Object.keys(prompts) as PromptKey[];
}

/**
 * Metadata about the sync
 */
export const syncMetadata = {
  syncedAt: ${syncedAt},
  syncedAtISO: "${timestamp}",
  promptCount: ${prompts.length},
} as const;
`;
}

