/**
 * YAML format generator
 */

import type { Prompt } from "../types";

/**
 * Escape YAML special characters
 */
function escapeYaml(str: string): string {
  // If string contains special characters, wrap in quotes
  if (/[:\{\}\[\],&*#?|\-<>=!%@`]/.test(str) || str.includes("\n")) {
    return `"${str.replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
  }
  return str;
}

/**
 * Convert value to YAML format
 */
function toYamlValue(value: any, indent: number = 0): string {
  const spaces = "  ".repeat(indent);

  if (value === null || value === undefined) {
    return "null";
  }

  if (typeof value === "string") {
    // Multi-line strings
    if (value.includes("\n")) {
      const lines = value.split("\n");
      return `|\n${lines.map((line) => `${spaces}  ${line}`).join("\n")}`;
    }
    return escapeYaml(value);
  }

  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return (
      "\n" +
      value.map((item) => `${spaces}- ${toYamlValue(item, indent + 1)}`).join("\n")
    );
  }

  if (typeof value === "object") {
    const entries = Object.entries(value).filter(([_, v]) => v !== undefined);
    if (entries.length === 0) return "{}";
    return (
      "\n" +
      entries
        .map(([k, v]) => {
          const yamlValue = toYamlValue(v, indent + 1);
          if (yamlValue.startsWith("\n")) {
            return `${spaces}${k}:${yamlValue}`;
          }
          return `${spaces}${k}: ${yamlValue}`;
        })
        .join("\n")
    );
  }

  return String(value);
}

/**
 * Generate YAML file content from prompts
 */
export function generateYAML(prompts: Prompt[], syncedAt: number, projectId: string): string {
  const timestamp = new Date(syncedAt).toISOString();

  let yaml = `# Auto-generated by ForPrompt SDK - DO NOT EDIT
# Last synced: ${timestamp}

_meta:
  syncedAt: ${syncedAt}
  syncedAtISO: "${timestamp}"
  projectId: "${projectId}"
  promptCount: ${prompts.length}

prompts:
`;

  for (const prompt of prompts) {
    yaml += `  ${prompt.key}:\n`;
    yaml += `    key: "${prompt.key}"\n`;
    yaml += `    name: "${prompt.name}"\n`;

    if (prompt.description) {
      yaml += `    description: ${toYamlValue(prompt.description, 2)}\n`;
    }

    yaml += `    versionNumber: ${prompt.versionNumber}\n`;

    // System prompt (multi-line)
    if (prompt.systemPrompt.includes("\n")) {
      yaml += `    systemPrompt: |\n`;
      const lines = prompt.systemPrompt.split("\n");
      for (const line of lines) {
        yaml += `      ${line}\n`;
      }
    } else {
      yaml += `    systemPrompt: ${toYamlValue(prompt.systemPrompt, 2)}\n`;
    }

    yaml += `    updatedAt: ${prompt.updatedAt}\n`;

    // Optional fields
    if (prompt.purpose) {
      yaml += `    purpose: ${toYamlValue(prompt.purpose, 2)}\n`;
    }
    if (prompt.expectedBehavior) {
      yaml += `    expectedBehavior: ${toYamlValue(prompt.expectedBehavior, 2)}\n`;
    }
    if (prompt.inputFormat) {
      yaml += `    inputFormat: ${toYamlValue(prompt.inputFormat, 2)}\n`;
    }
    if (prompt.outputFormat) {
      yaml += `    outputFormat: ${toYamlValue(prompt.outputFormat, 2)}\n`;
    }
    if (prompt.constraints) {
      yaml += `    constraints: ${toYamlValue(prompt.constraints, 2)}\n`;
    }
    if (prompt.useCases) {
      yaml += `    useCases: ${toYamlValue(prompt.useCases, 2)}\n`;
    }
    if (prompt.additionalNotes) {
      yaml += `    additionalNotes: ${toYamlValue(prompt.additionalNotes, 2)}\n`;
    }
    if (prompt.toolsNotes) {
      yaml += `    toolsNotes: ${toYamlValue(prompt.toolsNotes, 2)}\n`;
    }

    yaml += "\n";
  }

  return yaml;
}

